[32mINFO    [0m conftest:conftest.py:81 Starting a new test.
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 201 50
[32mINFO    [0m conftest:test_patch_orders.py:29 New order created with ID: mr0Ni1jV9Nm7WvzsSCcAj
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "PATCH /orders/mr0Ni1jV9Nm7WvzsSCcAj HTTP/11" 204 0
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
[35mDEBUG   [0m urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "GET /orders/mr0Ni1jV9Nm7WvzsSCcAj HTTP/11" 200 200
[32mINFO    [0m conftest:test_patch_orders.py:51 Successfully retrieved updated order: {'id': 'mr0Ni1jV9Nm7WvzsSCcAj', 'bookId': 1, 'customerName': 'automation user updated', 'createdBy': '6da547055d4296961bf1a522bbac681e5431762b32b5b0db441c62fc35843530', 'quantity': 1, 'timestamp': 1726891829001}
[32mINFO    [0m conftest:conftest.py:83 Finished the test.