DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "POST /api-clients/ HTTP/11" 201 82
INFO     conftest:conftest.py:81 Starting a new test.
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 201 50
INFO     conftest:test_patch_orders.py:29 New order created with ID: aaXr2V15hpGyt_c68gqzC
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "PATCH /orders/aaXr2V15hpGyt_c68gqzC HTTP/11" 204 0
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "GET /orders/aaXr2V15hpGyt_c68gqzC HTTP/11" 200 200
INFO     conftest:test_patch_orders.py:51 Successfully retrieved updated order: {'id': 'aaXr2V15hpGyt_c68gqzC', 'bookId': 1, 'customerName': 'automation user updated', 'createdBy': 'e46cc4822a5211d43d96c5af9dd9a2ab86fa93adb0051c0bf1b07035c758ecee', 'quantity': 1, 'timestamp': 1726896828536}
INFO     conftest:conftest.py:83 Finished the test.