INFO     conftest:conftest.py:81 Starting a new test.
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "POST /orders HTTP/11" 201 50
INFO     conftest:test_get_orders.py:28 New order created with ID: LQBl-Yj-LiyHu3gXI4dA9
DEBUG    urllib3.connectionpool:connectionpool.py:1051 Starting new HTTPS connection (1): simple-books-api.glitch.me:443
DEBUG    urllib3.connectionpool:connectionpool.py:546 https://simple-books-api.glitch.me:443 "GET /orders/LQBl-Yj-LiyHu3gXI4dA9 HTTP/11" 200 192
INFO     conftest:test_get_orders.py:44 Successfully retrieved order: {'id': 'LQBl-Yj-LiyHu3gXI4dA9', 'bookId': 1, 'customerName': 'automation user', 'createdBy': '9ad28ce77d8e769b24a9be8db84f08ff6e999fa0529730046cdf7e66d9ceb99b', 'quantity': 1, 'timestamp': 1726891867470}
INFO     conftest:conftest.py:83 Finished the test.